/**
 * ZERA Wallet Creation Constants
 * 
 * ⚠️  CRITICAL SECURITY NOTICE: BIP44 INCOMPATIBILITY  ⚠️
 * 
 * This implementation uses SLIP-0010 hardened derivation paths, which are
 * FUNDAMENTALLY INCOMPATIBLE with standard BIP44 wallets.
 * 
 * WHY THIS INCOMPATIBILITY EXISTS:
 * - EdDSA curves (Ed25519/Ed448) CANNOT perform public key derivation
 * - Mixed hardened/normal derivation creates security vulnerabilities
 * - Full hardening is a cryptographic requirement, not a design choice
 * 
 * BIP44 PATH:     m/44/1110/0/0/0 (mixed hardened/normal)
 * OUR PATH:       m/44'/1110'/0'/0'/0' (all hardened)
 * 
 * IMPACT: Addresses generated by BIP44 wallets cannot be reproduced by our
 * system and vice versa. This is a necessary security trade-off.
 * 
 * STANDARDS: We follow SLIP-0010 (de-facto standard for EdDSA HD wallets)
 */

// ============================================================================
// IMPORTS FROM SHARED CRYPTO MODULE
// ============================================================================

// Import cryptographic constants from shared module
import {
  KEY_TYPE,
  HASH_TYPE,
  VALID_KEY_TYPES,
  VALID_HASH_TYPES,
  KEY_TYPE_PREFIXES,
  HASH_TYPE_PREFIXES,
  isValidKeyType,
  isValidHashType
} from '../shared/crypto/constants.js';

// Re-export for external use
export type {
  KeyType,
  HashType
} from '../shared/crypto/constants.js';

export {
  KEY_TYPE,
  HASH_TYPE,
  VALID_KEY_TYPES,
  VALID_HASH_TYPES,
  KEY_TYPE_PREFIXES,
  HASH_TYPE_PREFIXES,
  isValidKeyType,
  isValidHashType
};

// ============================================================================
// WALLET-SPECIFIC TYPE DEFINITIONS
// ============================================================================

export type MnemonicLength = 12 | 15 | 18 | 21 | 24;

// ============================================================================
// NETWORK CONSTANTS
// ============================================================================

export const ZERA_TYPE = 1110; // SLIP44 coin type for ZRA
export const ZERA_TYPE_HEX = '0x80000456';
export const ZERA_SYMBOL = 'ZRA';
export const ZERA_NAME = 'ZERA';

// ============================================================================
// WALLET-SPECIFIC CONSTANTS
// ============================================================================

// BIP39 supported mnemonic lengths
export const MNEMONIC_LENGTHS: readonly MnemonicLength[] = [12, 15, 18, 21, 24];

// ============================================================================
// DERIVATION CONSTANTS
// ============================================================================

// SLIP-0010 derivation path for Ed25519/Ed448 (fully hardened)
// ⚠️  WARNING: This is NOT BIP44 compatible due to EdDSA security requirements
export const SLIP0010_DERIVATION_PATH = `m/44'/${ZERA_TYPE}'/0'/0'/0'`;

// Only valid derivation scheme for Ed25519/Ed448
export const DERIVATION_SCHEME = 'slip0010';

// Default HD wallet settings
export const DEFAULT_HD_SETTINGS = {
  accountIndex: 0,
  changeIndex: 0,
  addressIndex: 0
} as const;

// ============================================================================
// EXTENDED KEY VERSIONS
// ============================================================================

// ZERA extended key version bytes (custom to prevent cross-chain confusion)
export const EXTENDED_KEY_VERSIONS = {
  PRIVATE: 0x04b2430c, // ZERA private key version
  PUBLIC: 0x04b2430d   // ZERA public key version
} as const;

// ============================================================================
// ERROR MESSAGES
// ============================================================================

export const ERROR_MESSAGES = {
  INVALID_KEY_TYPE: `Invalid key type. Must be one of: ${VALID_KEY_TYPES.join(', ')}`,
  INVALID_HASH_TYPE: `Invalid hash type. Must be one of: ${VALID_HASH_TYPES.join(', ')}`,
  INVALID_MNEMONIC_LENGTH: `Invalid mnemonic length. Must be one of: ${MNEMONIC_LENGTHS.join(', ')}`,
  INVALID_MNEMONIC: 'Invalid BIP39 mnemonic phrase',
  INVALID_DERIVATION_PATH: 'Invalid derivation path format',
  INVALID_ACCOUNT_INDEX: 'Account index must be a non-negative integer',
  INVALID_CHANGE_INDEX: 'Change index must be 0 or 1',
  INVALID_ADDRESS_INDEX: 'Address index must be a non-negative integer',
  MNEMONIC_REQUIRED: 'Mnemonic phrase is required',
  KEY_TYPE_REQUIRED: 'Key type is required',
  HASH_TYPES_REQUIRED: 'Hash types array is required'
} as const;

// ============================================================================
// WALLET-SPECIFIC VALIDATION FUNCTIONS
// ============================================================================

export function isValidMnemonicLength(length: MnemonicLength): boolean {
  return MNEMONIC_LENGTHS.includes(length);
}

export function validateSLIP0010Path(path: string): boolean {
  if (!path) return false;
  if (!path.startsWith('m/')) return false;
  
  const parts = path.split('/');
  if (parts.length !== 6) return false;
  
  try {
    // All components must be hardened
    for (let i = 1; i < parts.length; i++) {
      if (!parts[i]?.endsWith("'")) return false;
    }
    
    // Purpose must be 44
    if (parseInt(parts[1]?.slice(0, -1) || '0') !== 44) return false;
    
    // Coin type must be ZERA (1110)
    if (parseInt(parts[2]?.slice(0, -1) || '0') !== ZERA_TYPE) return false;
    
    return true;
  } catch {
    return false;
  }
}